preprocess_params = [
    {"name": "use_lincs",
     "type": bool,
     "default": True,
     "help": "Flag to indicate if landmark genes are used for gene selection.",
     },
    {"name": "scaling",
     "type": str,
     "default": "std",
     "choice": ["std", "minmax", "miabs", "robust"],
     "help": "Scaler for gene expression and Mordred descriptors data.",
     },
    {"name": "ge_scaler_fname",
     "type": str,
     "default": "x_data_gene_expression_scaler.gz",
     "help": "File name to save the gene expression scaler object.",
     },
    {"name": "default_data_url",
     "type": str,
     "default": "'https://ftp.mcs.anl.gov/pub/candle/public/improve/reproducability/DeepTTC/'",
     "help": "Link to model-specific data",
     },
    {"name": "sample_col_name",
     "type": str,
     "default": "COSMIC_ID",
     "help": "ID format of the samples",
     },
]

train_params = [
    {
        "name": "save_data",
        "type": bool,
        "default": False,
        "help": "Whether to save loaded data in pickle files",
    },
    {
        "name": "use_lincs",
        "type": bool,
        "default": False,
        "help": "Whether to use a LINCS subset of genes ONLY",
    },
    {
        "name": "benchmark_dir",
        "type": str,
        "default": None,
        "help": "Directory with the input data for benchmarking",
    },
    {
        "name": "benchmark_result_dir",
        "type": str,
        "default": None,
        "help": "Directory for benchmark output",
    },
    {
        "name": "generate_input_data",
        "type": bool,
        "default": None,
        "help": "'True' for generating input data anew, 'False' for using stored data",
    },
    {
        "name": "mode",
        "type": str,
        "default": None,
        "help": "Execution mode. Available modes are: 'run', 'benchmark'",
    },
    {
        "name": "cancer_id",
        "type": str,
        "default": None,
        "help": "Column name for cancer",
    },
    {
        "name": "drug_id",
        "type": str,
        "default": None,
        "help": "Column name for drug",
    },
    {
        "name": "sample_id",
        "type": str,
        "default": None,
        "help": "Column name for samples/cell lines",
    },
    {
        "name": "target_id",
        "type": str,
        "default": None,
        "help": "Column name for target",
    },
    {
        "name": "train_data_drug",
        "type": str,
        "default": None,
        "help": "Drug data for training",
    },
    {
        "name": "test_data_drug",
        "type": str,
        "default": None,
        "help": "Drug data for testing",
    },
    {
        "name": "train_data_rna",
        "type": str,
        "default": None,
        "help": "RNA data for training",
    },
    {
        "name": "test_data_rna",
        "type": str,
        "default": None,
        "help": "RNA data for testing",
    },
    {
        "name": "vocab_dir",
        "type": str,
        "default": None,
        "help": "Directory with ESPF vocabulary",
    },
    {
        "name": "transformer_num_attention_heads_drug",
        "type": int,
        "default": None,
        "help": "number of attention heads for drug transformer",
    },
    {
        "name": "input_dim_drug",
        "type": int,
        "default": None,
        "help": "Input size of the drug transformer",
    },
    {
        "name": "transformer_emb_size_drug",
        "type": int,
        "default": None,
        "help": "Size of the drug embeddings",
    },
    {
        "name": "transformer_n_layer_drug",
        "type": int,
        "default": None,
        "help": "Number of layers for drug transformer",
    },
    {
        "name": "transformer_intermediate_size_drug",
        "type": int,
        "default": None,
        "help": "Intermediate size of the drug layers",
    },
    {
        "name": "transformer_attention_probs_dropout",
        "type": float,
        "default": None,
        "help": "number of layers for drug transformer",
    },
    {
        "name": "transformer_hidden_dropout_rate",
        "type": float,
        "default": None,
        "help": "dropout rate for transformer hidden layers",
    },
    {
        "name": "dropout",
        "type": float,
        "default": None,
        "help": "dropout rate for common part",
    },
    {
        "name": "input_dim_drug_classifier",
        "type": int,
        "default": None,
        "help": "input dimensions for drug classifier",
    },
    {
        "name": "input_dim_gene_classifier",
        "type": int,
        "default": None,
        "help": "input dimensions for gene classifier",
    },
    {
        "name": "gene_dim",
        "type": int,
        "default": None,
        "help": "Dimensions of the input gene expression data",
    },
]

test_params = []
